### ISSUE TITLE
Error in harmonyObj$cluster_cpp(): element-wise pow()

### ISSUE THREAD

**Issue by Mihkorz** [immunogenomics/harmony#167]
Hi!

I'm trying to repeat tutorial [Batch Effect Correction in Chromium Single Cell ATAC Data](https://www.10xgenomics.com/resources/analysis-guides/batch-effect-correction-in-chromium-single-cell-atac-data)

But on the Batch correction step I encounter the following error:
```
Harmony 1/10

Error in harmonyObj$cluster_cpp(): element-wise pow(): incompatible matrix dimensions: 100x2 and 2x1
Traceback:

1. RunHarmony(object = unintegrated, group.by.vars = "dataset", 
 .     reduction = "lsi", assay.use = "peaks_1", project.dim = FALSE)
2. RunHarmony.Seurat(object = unintegrated, group.by.vars = "dataset", 
 .     reduction = "lsi", assay.use = "peaks_1", project.dim = FALSE)
3. HarmonyMatrix(embedding, metavars_df, group.by.vars, FALSE, 0, 
 .     theta, lambda, sigma, nclust, tau, block.size, max.iter.harmony, 
 .     max.iter.cluster, epsilon.cluster, epsilon.harmony, plot_convergence, 
 .     FALSE, verbose, reference_values)
4. harmonize(harmonyObj, max.iter.harmony, verbose)
5. cluster(harmonyObj)
6. harmonyObj$cluster_cpp()
```
This seems quite strange to me since matrices with shapes 100x2 and 2x1 can be broadcast together
I was trying to run same pipeline on different set of datasets and still got the same error.

My configuration is as follows:
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

other attached packages:
 [1] GenomicRanges_1.48.0 GenomeInfoDb_1.32.4  IRanges_2.30.1      
 [4] S4Vectors_0.34.0     BiocGenerics_0.42.0  dplyr_1.0.10        
 [7] Signac_1.8.0         harmony_0.1.0        Rcpp_1.0.9          
[10] sp_1.5-0             SeuratObject_4.1.2   Seurat_4.2.0   
```

**Comment by saeidamiri1** [comment]
I got the same error: 
Harmony 1/20
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in harmonyObj$cluster_cpp() : 
  element-wise pow(): incompatible matrix dimensions: 100x2 and 2x1

**Comment by ianyfchang** [comment]
The CRAN check results showed many ERRORs (https://cran.r-project.org/web/checks/check_results_harmony.html).
I fixed the error by re-install harmony from the source code or devtools::install_github("immunogenomics/harmony").

**Comment by KforKuma** [comment]
Hi, if ur problem is not solved after reinstalling, please check this: https://github.com/immunogenomics/harmony/issues/169#issuecomment-1272314724

**Comment by Mihkorz** [comment]
> Hi, if ur problem is not solved after reinstalling, please check this: [#169 (comment)](https://github.com/immunogenomics/harmony/issues/169#issuecomment-1272314724)

Thanks a lot! 
It worked perfectly indeed!
